import unittest

from extract_title_md import extract_title_md

class TestExtractTitle(unittest.TestCase):
    def test_valid_case(self):
        lines = ['# Tolkien Fan Club\n', '\n', '![JRR Tolkien sitting](/images/tolkien.png)\n', '\n', "Here's the deal, **I like Tolkien**.\n", '\n', '> "I am in fact a Hobbit in all but size."\n', '>\n', '> -- J.R.R. Tolkien\n', '\n', '## Blog posts\n', '\n', '- [Why Glorfindel is More Impressive than Legolas](/blog/glorfindel)\n', '- [Why Tom Bombadil Was a Mistake](/blog/tom)\n', '- [The Unparalleled Majesty of "The Lord of the Rings"](/blog/majesty)\n', '\n', '## Reasons I like Tolkien\n', '\n', '- You can spend years studying the legendarium and still not understand its depths\n', '- It can be enjoyed by children and adults alike\n', "- Disney _didn't ruin it_ (okay, but Amazon might have)\n", '- It created an entirely new genre of fantasy\n', '\n', '## My favorite characters (in order)\n', '\n', '1. Gandalf\n', '2. Bilbo\n', '3. Sam\n', '4. Glorfindel\n', '5. Galadriel\n', '6. Elrond\n', '7. Thorin\n', '8. Sauron\n', '9. Aragorn\n', '\n', "Here's what `elflang` looks like (the perfect coding language):\n", '\n', '```\n', 'func main(){\n', '    fmt.Println("Aiya, Ambar!")\n', '}\n', '```\n', '\n', 'Want to get in touch? [Contact me here](/contact).\n', '\n', 'This site was generated with a custom-built [static site generator](https://www.boot.dev/courses/build-static-site-generator-python) from the course on [Boot.dev](https://www.boot.dev).']
        self.assertEqual(extract_title_md(lines), "Tolkien Fan Club")
    def test_valid_case_inside_h1(self):
        lines = ['Tolkien Fan Club\n', '\n', '![JRR Tolkien sitting](/images/tolkien.png)\n', '\n', "# Here's the deal, **I like Tolkien**.\n", '\n', '> "I am in fact a Hobbit in all but size."\n', '>\n', '> -- J.R.R. Tolkien\n', '\n', '## Blog posts\n', '\n', '- [Why Glorfindel is More Impressive than Legolas](/blog/glorfindel)\n', '- [Why Tom Bombadil Was a Mistake](/blog/tom)\n', '- [The Unparalleled Majesty of "The Lord of the Rings"](/blog/majesty)\n', '\n', '## Reasons I like Tolkien\n', '\n', '- You can spend years studying the legendarium and still not understand its depths\n', '- It can be enjoyed by children and adults alike\n', "- Disney _didn't ruin it_ (okay, but Amazon might have)\n", '- It created an entirely new genre of fantasy\n', '\n', '## My favorite characters (in order)\n', '\n', '1. Gandalf\n', '2. Bilbo\n', '3. Sam\n', '4. Glorfindel\n', '5. Galadriel\n', '6. Elrond\n', '7. Thorin\n', '8. Sauron\n', '9. Aragorn\n', '\n', "Here's what `elflang` looks like (the perfect coding language):\n", '\n', '```\n', 'func main(){\n', '    fmt.Println("Aiya, Ambar!")\n', '}\n', '```\n', '\n', 'Want to get in touch? [Contact me here](/contact).\n', '\n', 'This site was generated with a custom-built [static site generator](https://www.boot.dev/courses/build-static-site-generator-python) from the course on [Boot.dev](https://www.boot.dev).']
        self.assertEqual(extract_title_md(lines), "Here's the deal, **I like Tolkien**.")
    def test_invalid_case(self):
        lines = [' Tolkien Fan Club\n', '\n', '![JRR Tolkien sitting](/images/tolkien.png)\n', '\n', "Here's the deal, **I like Tolkien**.\n", '\n', '> "I am in fact a Hobbit in all but size."\n', '>\n', '> -- J.R.R. Tolkien\n', '\n', '## Blog posts\n', '\n', '- [Why Glorfindel is More Impressive than Legolas](/blog/glorfindel)\n', '- [Why Tom Bombadil Was a Mistake](/blog/tom)\n', '- [The Unparalleled Majesty of "The Lord of the Rings"](/blog/majesty)\n', '\n', '## Reasons I like Tolkien\n', '\n', '- You can spend years studying the legendarium and still not understand its depths\n', '- It can be enjoyed by children and adults alike\n', "- Disney _didn't ruin it_ (okay, but Amazon might have)\n", '- It created an entirely new genre of fantasy\n', '\n', '## My favorite characters (in order)\n', '\n', '1. Gandalf\n', '2. Bilbo\n', '3. Sam\n', '4. Glorfindel\n', '5. Galadriel\n', '6. Elrond\n', '7. Thorin\n', '8. Sauron\n', '9. Aragorn\n', '\n', "Here's what `elflang` looks like (the perfect coding language):\n", '\n', '```\n', 'func main(){\n', '    fmt.Println("Aiya, Ambar!")\n', '}\n', '```\n', '\n', 'Want to get in touch? [Contact me here](/contact).\n', '\n', 'This site was generated with a custom-built [static site generator](https://www.boot.dev/courses/build-static-site-generator-python) from the course on [Boot.dev](https://www.boot.dev).']
        with self.assertRaises(Exception):
            extract_title_md(lines)
    def test_invalid_case_h1_no_space(self):
        lines = ['#Tolkien Fan Club\n', '\n', '![JRR Tolkien sitting](/images/tolkien.png)\n', '\n', "Here's the deal, **I like Tolkien**.\n", '\n', '> "I am in fact a Hobbit in all but size."\n', '>\n', '> -- J.R.R. Tolkien\n', '\n', '## Blog posts\n', '\n', '- [Why Glorfindel is More Impressive than Legolas](/blog/glorfindel)\n', '- [Why Tom Bombadil Was a Mistake](/blog/tom)\n', '- [The Unparalleled Majesty of "The Lord of the Rings"](/blog/majesty)\n', '\n', '## Reasons I like Tolkien\n', '\n', '- You can spend years studying the legendarium and still not understand its depths\n', '- It can be enjoyed by children and adults alike\n', "- Disney _didn't ruin it_ (okay, but Amazon might have)\n", '- It created an entirely new genre of fantasy\n', '\n', '## My favorite characters (in order)\n', '\n', '1. Gandalf\n', '2. Bilbo\n', '3. Sam\n', '4. Glorfindel\n', '5. Galadriel\n', '6. Elrond\n', '7. Thorin\n', '8. Sauron\n', '9. Aragorn\n', '\n', "Here's what `elflang` looks like (the perfect coding language):\n", '\n', '```\n', 'func main(){\n', '    fmt.Println("Aiya, Ambar!")\n', '}\n', '```\n', '\n', 'Want to get in touch? [Contact me here](/contact).\n', '\n', 'This site was generated with a custom-built [static site generator](https://www.boot.dev/courses/build-static-site-generator-python) from the course on [Boot.dev](https://www.boot.dev).']
        with self.assertRaises(Exception):
            extract_title_md(lines)